set global tabstop     4
set global indentwidth 4

# disable mouse (who thought this was a good idea...?)
set global ui_options ncurses_enable_mouse=false

# Highlight bad whitespace
add-highlighter -group / group trailing_white_spaces
add-highlighter -group /trailing_white_spaces regex \h+$ 0:Error

add-highlighter -group / group tabs
add-highlighter -group /tabs regex \t+ 0:Error

# Always show line numbers; initialize with bad whitespace shown
hook global WinCreate .* %{
    add-highlighter number_lines -hlcursor
	add-highlighter ref tabs
	add-highlighter ref trailing_white_spaces
}

# Enable these highlighters when not in insert
hook global InsertEnd .* %{
    add-highlighter ref tabs
    add-highlighter ref trailing_white_spaces
}

hook global InsertBegin .* %{
    remove-highlighter tabs
    remove-highlighter trailing_white_spaces
}

# jj to escape insert mode
hook global InsertChar j %{ try %{
  exec -draft hH <a-k>jj<ret> d
  exec <esc>
}}
