set global tabstop     4
set global indentwidth 4

# disable mouse (who thought this was a good idea...?)
set global ui_options ncurses_enable_mouse=false

# Highlight bad whitespace
add-highlighter shared/bad_whitespace group -passes colorize|move|wrap
add-highlighter shared/bad_whitespace/trailing regex \h+$ 0:Error
add-highlighter shared/bad_whitespace/tabs show-whitespaces -spc ' ' -nbsp ' ' -lf ' '

# show bad whitespace on startup
hook global WinCreate .* %{
    add-highlighter window/bad_whitespace ref bad_whitespace
}

# use spaces instead of tabs
#
hook global InsertChar \t %{
    exec -draft -itersel h@
}

hook global WinCreate .*/COMMIT_EDITMSG %{
    add-highlighter window/ column 50 default,blue
    set buffer autowrap_column 72
    autowrap-enable
}

# Enable these highlighters when not in insert
hook global InsertEnd .* %{
    add-highlighter window/bad_whitespace ref bad_whitespace
}

hook global InsertBegin .* %{
    remove-highlighter window/bad_whitespace
}

# jj to escape insert mode
hook global InsertChar k %{ try %{
  exec -draft hH <a-k>jk<ret> d
  exec <esc>
}}
